# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('ingredients', models.ManyToManyField(to='recipeAPI.Ingredient')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipeAPI.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeAPI.Station'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='item',
            field=models.ManyToManyField(to='recipeAPI.Item'),
        ),
    ]
