# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='item',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipeAPI.Item'),
        ),
    ]
