# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
