# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeAPI', '0002_auto_20170407_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_station', to='recipeAPI.Item'),
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
